version: '3.8'

services:
  autopia-server:
    build: .
    container_name: autopia-server
    restart: always
    network_mode: host
    privileged: true
    volumes:
      - .:/app
      - /dev/input:/dev/input
    devices:
      - /dev/video0:/dev/video0
    environment:
      - SDL_VIDEODRIVER=dummy
